#!/bin/bash
gem uninstall  web-console -v=3.7.0
gem uninstall  uglifier -v=4.1.20 
gem uninstall  turbolinks -v=5.2.0 
gem uninstall  turbolinks-source -v=5.2.0 
gem uninstall  sqlite3 -v=1.4.0 
gem uninstall  spring-watcher-listen -v=2.0.1 
gem uninstall  spring -v=2.0.2 
gem uninstall  selenium-webdriver -v=3.141.0 
gem uninstall  sass-rails -v=5.0.7 
gem uninstall  tilt -v=2.0.9 
gem uninstall  sass -v=3.7.4 
gem uninstall  sass-listen -v=4.0.0 
gem uninstall  rubyzip -v=1.2.2 
gem uninstall  rails -v=5.2.3 
gem uninstall  sprockets-rails -v=3.2.1 
gem uninstall  sprockets -v=3.7.2 
gem uninstall  puma -v=3.12.1 
gem uninstall  listen -v=3.1.5 
gem uninstall  ruby_dep -v=1.5.0 
gem uninstall  rb-inotify -v=0.10.0 
gem uninstall  rb-fsevent -v=0.10.3 
gem uninstall  jbuilder -v=2.8.0 
gem uninstall  multi_json -v=1.13.1 
gem uninstall  coffee-rails -v=4.2.2 
gem uninstall  railties -v=5.2.3 
gem uninstall  thor -v=0.20.3 
gem uninstall  method_source -v=0.9.2 
gem uninstall  coffee-script -v=2.4.1 
gem uninstall  execjs -v=2.7.0 
gem uninstall  coffee-script-source -v=1.12.2 
gem uninstall  chromedriver-helper -v=2.1.1 
gem uninstall  childprocess -v=0.9.0 
gem uninstall  ffi -v=1.10.0 
gem uninstall  capybara -v=3.16.2 
gem uninstall  xpath -v=3.2.0 
gem uninstall  regexp_parser -v=1.4.0 
gem uninstall  byebug -v=11.0.1 
gem uninstall  bootsnap -v=1.4.3 
gem uninstall  msgpack -v=1.2.9 
gem uninstall  bindex -v=0.7.0 
gem uninstall  archive-zip -v=0.12.0 
gem uninstall  io-like -v=0.3.0 
gem uninstall  addressable -v=2.6.0 
gem uninstall  public_suffix -v=3.0.3 
gem uninstall  activestorage -v=5.2.3 
gem uninstall  marcel -v=0.3.3 
gem uninstall  mimemagic -v=0.3.3 
gem uninstall  activerecord -v=5.2.3 
gem uninstall  arel -v=9.0.0 
gem uninstall  activemodel -v=5.2.3 
gem uninstall  actionmailer -v=5.2.3 
gem uninstall  mail -v=2.7.1 
gem uninstall  mini_mime -v=1.0.1 
gem uninstall  activejob -v=5.2.3 
gem uninstall  globalid -v=0.4.2 
gem uninstall  actioncable -v=5.2.3 
gem uninstall  websocket-driver -v=0.7.0 
gem uninstall  websocket-extensions -v=0.1.3 
gem uninstall  nio4r -v=2.3.1 
gem uninstall  actionpack -v=5.2.3 
gem uninstall  rack-test -v=1.1.0 
gem uninstall  rack 2.0.7
gem uninstall  actionview 5.2.3
gem uninstall  rails-html-sanitizer 1.0.4
gem uninstall  loofah 2.2.3
gem uninstall  crass 1.0.4
